export const initialEarnings = [
  {
    id: 'earn-101',
    trainerId: 'trn-1',
    trainerName: 'Arun Prakash',
    trainerEmail: 'arun@lurnstack.com',
    sessionId: 'ses-101',
    sessionTitle: 'React Hooks Masterclass',
    paidStudents: 28,
    sessionPrice: 149900,
    trainerShare: 65,
    refundAdjustment: 149900,
    status: 'requested',
    date: '2026-06-01',
  },
  {
    id: 'earn-102',
    trainerId: 'trn-2',
    trainerName: 'Meena Raj',
    trainerEmail: 'meena@lurnstack.com',
    sessionId: 'ses-102',
    sessionTitle: 'Advanced Node API Design',
    paidStudents: 16,
    sessionPrice: 199900,
    trainerShare: 60,
    refundAdjustment: 0,
    status: 'unpaid',
    date: '2026-06-03',
  },
  {
    id: 'earn-103',
    trainerId: 'trn-3',
    trainerName: 'Karthik Dev',
    trainerEmail: 'karthik@lurnstack.com',
    sessionId: 'ses-103',
    sessionTitle: 'AWS Deployment Bootcamp',
    paidStudents: 12,
    sessionPrice: 249900,
    trainerShare: 70,
    refundAdjustment: 249900,
    status: 'paid',
    date: '2026-05-26',
  },
  {
    id: 'earn-104',
    trainerId: 'trn-1',
    trainerName: 'Arun Prakash',
    trainerEmail: 'arun@lurnstack.com',
    sessionId: 'ses-104',
    sessionTitle: 'Frontend Interview Sprint',
    paidStudents: 9,
    sessionPrice: 99900,
    trainerShare: 65,
    refundAdjustment: 0,
    status: 'processing',
    date: '2026-06-06',
  },
];

export const initialSessions = [
  {
    id: 'ses-101',
    title: 'React Hooks Masterclass',
    trainerName: 'Arun Prakash',
    price: 149900,
    trainerShare: 65,
    paidStudents: 28,
    updatedAt: '2026-05-30',
  },
  {
    id: 'ses-102',
    title: 'Advanced Node API Design',
    trainerName: 'Meena Raj',
    price: 199900,
    trainerShare: 60,
    paidStudents: 16,
    updatedAt: '2026-06-02',
  },
  {
    id: 'ses-103',
    title: 'AWS Deployment Bootcamp',
    trainerName: 'Karthik Dev',
    price: 249900,
    trainerShare: 70,
    paidStudents: 12,
    updatedAt: '2026-05-24',
  },
];

export const initialAccounts = [
  {
    id: 'acct-1',
    trainerId: 'trn-1',
    trainerName: 'Arun Prakash',
    email: 'arun@lurnstack.com',
    accountHolder: 'Arun Prakash',
    bankName: 'HDFC Bank',
    accountNumber: '50200044327891',
    ifsc: 'HDFC0001234',
    upi: 'arun@upi',
    pan: 'ABCDE1234F',
    phone: '+91 98765 43210',
    status: 'verified',
    locked: true,
    history: [{ at: '2026-05-28', status: 'verified', admin: 'Admin User', note: 'PAN and IFSC matched.' }],
  },
  {
    id: 'acct-2',
    trainerId: 'trn-2',
    trainerName: 'Meena Raj',
    email: 'meena@lurnstack.com',
    accountHolder: 'Meena Raj',
    bankName: 'ICICI Bank',
    accountNumber: '621782003459',
    ifsc: 'ICIC0000788',
    upi: 'meena.raj@okicici',
    pan: 'PQRSX7789L',
    phone: '+91 99887 66554',
    status: 'pending',
    locked: false,
    history: [{ at: '2026-06-04', status: 'submitted', admin: 'System', note: 'Trainer submitted payout account.' }],
  },
];

export const initialPayouts = [
  {
    id: 'pay-201',
    trainerId: 'trn-1',
    trainerName: 'Arun Prakash',
    requestedAmount: 2896200,
    availableBalance: 4137100,
    requestedDate: '2026-06-05',
    status: 'requested',
    accountSnapshot: 'HDFC Bank ****7891, UPI arun@upi',
    adminNote: '',
    utr: '',
    paidDate: '',
  },
  {
    id: 'pay-202',
    trainerId: 'trn-3',
    trainerName: 'Karthik Dev',
    requestedAmount: 1889300,
    availableBalance: 1889300,
    requestedDate: '2026-06-02',
    status: 'approved',
    accountSnapshot: 'Axis Bank ****4470, UPI karthik@axis',
    adminNote: 'Approved for current payout cycle.',
    utr: '',
    paidDate: '',
  },
  {
    id: 'pay-203',
    trainerId: 'trn-4',
    trainerName: 'Divya S',
    requestedAmount: 760000,
    availableBalance: 760000,
    requestedDate: '2026-05-24',
    status: 'paid',
    accountSnapshot: 'SBI ****8842, UPI divya@sbi',
    adminNote: 'Manual NEFT completed.',
    utr: 'N158260448911',
    paidDate: '2026-05-26',
  },
];

export const initialRefunds = [
  {
    id: 'ref-1',
    trainerName: 'Arun Prakash',
    sessionTitle: 'React Hooks Masterclass',
    paymentId: 'pay_gateway_8841',
    amount: 149900,
    earningStatus: 'unpaid',
    adjustmentState: 'adjusted',
    reason: 'Student refund before payout approval.',
  },
  {
    id: 'ref-2',
    trainerName: 'Karthik Dev',
    sessionTitle: 'AWS Deployment Bootcamp',
    paymentId: 'pay_gateway_7201',
    amount: 249900,
    earningStatus: 'paid',
    adjustmentState: 'future_adjustment',
    reason: 'Trainer earning already settled; deduct in next payout.',
  },
];

export const initialAuditLog = [
  {
    id: 'audit-1',
    action: 'refund adjusted',
    admin: 'Admin User',
    timestamp: '2026-06-06 10:35',
    oldStatus: 'unpaid',
    newStatus: 'adjusted',
    note: 'Refund reduced unpaid payable amount.',
  },
  {
    id: 'audit-2',
    action: 'payout approved',
    admin: 'Finance Admin',
    timestamp: '2026-06-05 16:10',
    oldStatus: 'requested',
    newStatus: 'approved',
    note: 'Approved after balance and account verification.',
  },
  {
    id: 'audit-3',
    action: 'account verified',
    admin: 'Admin User',
    timestamp: '2026-05-28 12:20',
    oldStatus: 'pending',
    newStatus: 'verified',
    note: 'Bank details verified manually.',
  },
];
